### ISSUE TITLE
Found several bugs need fix

### ISSUE THREAD

**Issue by chiehhanl** [zactodd/dataset_maker#2]
@zactodd 

Thanks for your effort! I've found some bugs while I'm using your repo as below.

1. Input argument "annotation_dir" in both `instance_segemenation_format_conversion.py` and `localisation_format_conversion.py` is missing an "s". It should be "annotations_dir".
2. Line 307 in `instance_segmentation.py` 
`with Image.OPEN(f"{image_dir}/{image_info['file_name']}") as image:` should be corrected to `with Image.open(f"{image_dir}/{image_info['file_name']}") as image:`

**Comment by zactodd** [comment]
Thank you ill have a look and make those changes
